### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1 after running 

### ISSUE THREAD

**Issue by ghost** [chrismonit/SubRecon#1]
Good day. I am attempting to use SubRecon with a typical fasta file and a newick tree file. Upon running SubRecon with the following parameters

`java -jar SubRecon.jar -s cluster_0.fasta -t rooted_tree_new.new -m jtt -k 4 -a 0.42 > out1.txt`

the terminal gives 

`java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at subrecon.SubRecon.run(Unknown Source)
        at subrecon.SubRecon.main(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at pal.alignment.SimpleAlignment.getData(Unknown Source)
        at subrecon.molevo.AdvancedAlignmentAminoAcid.getStateBySequenceName(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.downTreeMarginal(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.downTreeMarginal(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.downTreeMarginal(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.recon(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
        at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

My output file is also contains the following
`[HEADER]	site	ln[P(D|theta,alpha)]	P(A=a,B=b|D,theta,alpha)
ERROR: Site 1
ERROR: Site 2
ERROR: Site 3
ERROR: Site 4
ERROR: Site 5
ERROR: Site 6
ERROR: Site 7
ERROR: Site 8
ERROR: Site 9
ERROR: Site 10`

**Comment by chrismonit** [comment]
Hi there, could you show/attach the alignment and tree files you are using? Without these it is difficult to work out the source of the problem

**Comment by nagarnoopur** [comment]
Hi
I am facing the same issue with dataset. It would be really helpful if you can help in rectifying it.

The command/parameters given for the run are:
`java -jar SubRecon1.0.jar -s mcpSR3.fas -t mcpSR3_fin.raxml.bootstraps.tre -m wag -k 4 -a 0.5 > subrecon.out.txt`

the output on terminal is:
```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at subrecon.SubRecon.run(Unknown Source)
	at subrecon.SubRecon.main(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at subrecon.utils.Utils.getLnSumComponents(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.recon(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at subrecon.SubRecon.run(Unknown Source)
	at subrecon.SubRecon.main(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at subrecon.utils.Utils.getLnSumComponents(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.recon(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at subrecon.SubRecon.run(Unknown Source)
	at subrecon.SubRecon.main(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at subrecon.utils.Utils.getLnSumComponents(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.recon(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at subrecon.recon.JointBranchReconstruction.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
The result and input files (zip file) are as follows:
[subrecon.out.txt](https://github.com/user-attachments/files/16614397/subrecon.out.txt)
[mcp3SR_.zip](https://github.com/user-attachments/files/16614405/mcp3SR_.zip)
